name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore Solutions/Posts.sln/Posts.sln
      
    - name: Build
      run: dotnet build Solutions/Posts.sln/Posts.sln --no-restore --configuration Release
      
    - name: Run Tests (with Testcontainers)
      run: |
        dotnet test Solutions/Posts.sln/Posts.sln \
          --no-build \
          --configuration Release \
          --logger trx \
          --results-directory TestResults \
          --verbosity normal
          
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: TestResults/*.trx